### ISSUE TITLE
Windows OR Linux 

### ISSUE THREAD

**Issue by wangsl613** [atomly-materials-research-lab/GPTFF#3]
Hello, developers, I would like to ask if GPTFF is only applicable to Linux and not supported on Windows?

**Comment by wangsl613** [comment]
![image](https://github.com/user-attachments/assets/d43c07ad-91da-4417-90a1-2f8f7484ee33)
and In the case of a version of GCC that is too high, an error should be reported, I think?

**Comment by fkxie** [comment]
Try to install `g++` compiler on your server, for example, try `conda install -c conda-forge gxx`

**Comment by fkxie** [comment]
fankai xie ***@***.***>于2024年8月14日 周三21:48写道：

**Comment by wangsl613** [comment]
OK! thank you very much for your suggestion, I will try it later

**Comment by 13yong** [comment]
## Hello， developers. I had met the same error!

"
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for gptff
Failed to build gptff
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (gptff)
"

### My python version is _3.8.20_
### My gcc version is _gcc (conda-forge gcc 14.2.0-1) 14.2.0_
